# Generated by Django 5.2.4 on 2025-08-05 17:37

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug da Categoria')),
                ('ordem', models.IntegerField(default=0, verbose_name='Ordem no Menu Principal')),
            ],
            options={
                'verbose_name': 'Categoria de Menu',
                'verbose_name_plural': 'Categorias de Menu',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Página')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug da Página')),
                ('conteudo', ckeditor.fields.RichTextField(verbose_name='Conteúdo da Página')),
                ('publicado', models.BooleanField(default=True, verbose_name='Página Publicada?')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paginas', to='pages.categoriamenu', verbose_name='Categoria Principal')),
            ],
            options={
                'verbose_name': 'Página',
                'verbose_name_plural': 'Páginas',
                'ordering': ['titulo'],
            },
        ),
    ]
