# Generated by Django 5.2.4 on 2025-08-06 19:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeuModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Conteúdo')),
            ],
        ),
    ]
